import {calculateEstimate} from './pricing.js';
const input=document.getElementById('quantity'),plan=document.getElementById('plan'),error=document.getElementById('quantity-error'),result=document.getElementById('quote-result');
function line(text,cls){const p=document.createElement('p');p.textContent=text;if(cls)p.className=cls;result.append(p);}
function update(){const q=calculateEstimate(input.value,plan.value);result.replaceChildren();delete result.dataset.baseTotal;delete result.dataset.quoteState;error.hidden=q.ok||input.value==='';error.textContent=q.ok?'':q.error;input.setAttribute('aria-invalid',String(!q.ok&&input.value!==''));if(!q.ok){line('試算額を表示できません。入力をご確認ください。','muted');return;}const target=document.querySelector('[name=target]:checked')?.value||'closer',copy=document.querySelector('[name=copy]:checked')?.value||'bring',consultation=target!=='closer'||copy==='individual';line('基本料金：'+q.quantity.toLocaleString('ja-JP')+'件 × '+q.unitYen+'円 = '+q.totalYen.toLocaleString('ja-JP')+'円（税込）');if(consultation){line('総額：個別見積が必要です','estimate-total selected-estimate');line('追加の相談事項を含むため、上の基本料金は最終総額ではありません。','muted');}else{line('試算合計 '+q.totalYen.toLocaleString('ja-JP')+'円（税込）','estimate-total selected-estimate');line('提供条件の確認前の試算です。注文・契約は成立しません。','muted');}if(plan.value==='data_link')line('データ連携プランは準備中の予定価格です。','muted');result.dataset.quoteState=consultation?'needs_quote':'estimate';result.dataset.baseTotal=String(q.totalYen);}
input.addEventListener('input',update);plan.addEventListener('change',update);for(const i of document.querySelectorAll('[name=target],[name=copy]'))i.addEventListener('change',update);input.dataset.calculatorReady='true';update();

const next=document.getElementById('mock-next'),dialog=document.getElementById('mock-order'),mockQuantity=document.getElementById('mock-quantity'),summary=document.getElementById('mock-summary'),mockError=document.getElementById('mock-quantity-error');
function refreshSummary(){summary.replaceChildren();for(const text of [plan.options[plan.selectedIndex].textContent,document.querySelector('[name=target]:checked').closest('label').textContent,document.querySelector('[name=copy]:checked').closest('label').textContent,result.textContent]){const p=document.createElement('p');p.textContent=text;summary.append(p);}const q=calculateEstimate(mockQuantity.value,plan.value);mockError.hidden=q.ok;mockError.textContent=q.ok?'':q.error;}
next.addEventListener('click',()=>{const q=calculateEstimate(input.value,plan.value);if(!q.ok){input.focus();return;}mockQuantity.value=input.value;refreshSummary();dialog.showModal();mockQuantity.focus();});
mockQuantity.addEventListener('input',()=>{input.value=mockQuantity.value;update();refreshSummary();});
function clearMock(){document.getElementById('mock-business').value='';document.getElementById('mock-email').value='';summary.replaceChildren();}
document.getElementById('mock-back').addEventListener('click',()=>{clearMock();dialog.close();});
dialog.addEventListener('close',()=>{clearMock();next.focus();});
