import {calculateEstimate} from './pricing.js';
import {classifyPaymentAmount} from './payment-amount.js';
const $=id=>document.getElementById(id),key='closer-preview-order-config-v1';let step=1,busy=false;const allowed={target:['closer','region','list','advanced'],copy:['bring','common','individual'],shortage:['supplement','list_only']};
const chosen=name=>document.querySelector(`[name="${name}"]:checked`);const config=()=>({quantity:$('order-quantity').value,target:chosen('target').value,copy:chosen('copy').value,shortage:chosen('shortage').value});
const quote=()=>{const c=config(),q=calculateEstimate(c.quantity,'regular');return {...q,needsQuote:c.target!=='closer'||c.copy==='individual'};};
function append(node,text,cls){const p=document.createElement('p');p.textContent=text;if(cls)p.className=cls;node.append(p);}
function persist(){try{sessionStorage.setItem(key,JSON.stringify(config()));}catch{}}
function update(){const c=config(),q=quote();$('region-fields').hidden=c.target!=='region';$('list-fields').hidden=c.target!=='list';$('order-quote').replaceChildren();$('order-error').hidden=q.ok; $('order-error').textContent=q.ok?'':q.error;$('order-quantity').setAttribute('aria-invalid',String(!q.ok));$('order-next').disabled=!q.ok;
 if(q.ok){append($('order-quote'),`基本内訳：受付成功 ${q.quantity.toLocaleString('ja-JP')}件 × 10円 = ${q.totalYen.toLocaleString('ja-JP')}円（税込）`);append($('order-quote'),q.needsQuote?'総額：個別見積が必要':`試算合計 ${q.totalYen.toLocaleString('ja-JP')}円（税込）`,'estimate-total selected-estimate');if(q.needsQuote)append($('order-quote'),'追加の相談条件を含むため、基本小計で最終注文はできません。','muted');}persist();}
function show(next,push=false){step=next;if(push)history.pushState({mockStep:next},'',next===1?'/order':next===2?'/order#confirm':'/order#test-mock');for(let i=1;i<=3;i++)$('step-'+i).hidden=i!==next;$('step-zero').hidden=next!=='zero';document.querySelectorAll('.order-steps li').forEach((el,i)=>{if(i+1===next)el.setAttribute('aria-current','step');else el.removeAttribute('aria-current');});document.body.dataset.orderStep=String(next);const heading=document.querySelector(next==='zero'?'#step-zero h2':'#step-'+next+' h2');heading.tabIndex=-1;heading.focus();scrollTo(0,0);}
function summary(){const c=config(),q=quote(),n=$('order-summary');n.replaceChildren();append(n,`受付成功 ${q.quantity}件`);append(n,chosen('target').closest('label').textContent);append(n,chosen('copy').closest('label').textContent);if(c.target==='region')append(n,`相談条件：地域 ${$('order-region').value||'未入力'} ／ 業種 ${$('order-industry').value||'未入力'}`);if(c.target==='list')append(n,chosen('shortage').closest('label').textContent);append(n,`基本内訳：${q.quantity}件 × 10円 = ${q.totalYen.toLocaleString('ja-JP')}円（税込）`);append(n,q.needsQuote?'総額：個別見積が必要':`試算合計 ${q.totalYen.toLocaleString('ja-JP')}円（税込）`,'total');append(n,`商材：${$('order-business').value}`);append(n,`送信者：${$('order-sender').value}`);append(n,`返信先：${$('order-email').value}`);append(n,'送信名義と最終文面は別途承認が必要です。');$('quote-branch').hidden=!q.needsQuote;$('order-test').disabled=true;$('order-approval').checked=false;}
try{const saved=JSON.parse(sessionStorage.getItem(key)||'null');if(saved){if(calculateEstimate(saved.quantity,'regular').ok)$('order-quantity').value=saved.quantity;for(const name of Object.keys(allowed))if(allowed[name].includes(saved[name]))document.querySelector(`[name="${name}"][value="${saved[name]}"]`).checked=true;}}catch{}
for(const i of document.querySelectorAll('#step-1 input,#step-1 textarea'))i.addEventListener('input',update);
$('order-next').addEventListener('click',()=>{if(step!==1||busy||!quote().ok)return;const missing=!$('order-business').value.trim()||!$('order-sender').value.trim()||!$('order-email').validity.valid||!$('order-email').value;if(missing){$('order-error').hidden=false;$('order-error').textContent='商材・送信者・返信先メールを入力してください（画面確認用）。';return;}busy=true;summary();show(2,true);busy=false;});
function paymentState(){const raw=$('mock-credit').value;if(!/^(0|[1-9][0-9]*)$/.test(raw))return null;try{return classifyPaymentAmount(quote().totalYen,Number(raw));}catch{return null;}}
function updatePayment(){const p=paymentState(),q=quote();$('order-test').disabled=!$('order-approval').checked||q.needsQuote||!p||p.route==='adjust_or_contact';$('order-test').textContent=p?.route==='independent_zero'?'0円フローの設計Previewへ':'テスト決済画面のmockへ';$('mock-payment-state').textContent=!p?'credit試算を確認してください。':p.route==='independent_zero'?'残額0円：Stripeを利用しない独立フロー（設計のみ）':p.route==='adjust_or_contact'?`残額${p.remainingYen}円：カード最低50円未満です。数量・creditを調整するかお問い合わせください。`:`カード試算残額 ${p.remainingYen.toLocaleString('ja-JP')}円（税込）／Stripe未接続`;}
$('order-back').addEventListener('click',()=>{if(step===2)show(1);});$('order-approval').addEventListener('change',updatePayment);$('mock-credit').addEventListener('input',updatePayment);
$('order-next').addEventListener('click',()=>{if(step===2)updatePayment();});
$('order-test').addEventListener('click',()=>{const p=paymentState();if(step!==2||busy||!$('order-approval').checked||quote().needsQuote||!p||p.route==='adjust_or_contact')return;busy=true;$('order-test').disabled=true;show(p.route==='independent_zero'?'zero':3,true);if(p.route==='card')document.body.dataset.mockTransitionCount=String(Number(document.body.dataset.mockTransitionCount||0)+1);busy=false;});
$('order-return').addEventListener('click',()=>{if(step!==3)return;$('order-approval').checked=false;$('order-test').disabled=true;show(2);});
addEventListener('popstate',e=>{const n=e.state?.mockStep;show(n===2&&!$('order-summary').textContent?1:n===1||n===2?n:1);$('order-approval').checked=false;$('order-test').disabled=true;});
addEventListener('pageshow',()=>{history.replaceState({mockStep:1},'','/order');show(1);$('order-approval').checked=false;$('order-test').disabled=true;});update();$('order-quantity').dataset.orderReady='true';show(1);
